### ISSUE TITLE
Use `redirect` instead of `render` for the poll that closed.

### ISSUE THREAD

**Issue by Jwizzed** [Nantawat6510545543/ku-polls#50]
When I try to access the URL of a poll that can't vote (Voting has ended) e.g.  http://xxx.x.x.x:8000/polls/2/ It will automatically bring me to the results page which is good but the URL doesn't change to the result (What I expected is http://xxx.x.x.x:8000/polls/2/results). So I think it would be good if you use `redirect` instead of `render`

**Comment by Nantawat6510545543** [comment]
Thank you, I have made the improvements according to your suggestions.
