### ISSUE TITLE
Consider using the same commands for installation instructions.

### ISSUE THREAD

**Issue by Jwizzed** [Nantawat6510545543/ku-polls#51]
I am a Mac user, I can run your installation in both script and manually and it's working well but I saw that in your installation.md the commands to activate the virtual environment are not the same
For Mac/Linux, you use `. venv/bin/activate` but in [linux-setup-script.sh](https://github.com/Nantawat6510545543/ku-polls/blob/main/linux-setup-script.sh), you use `source ./venv/bin/activate`

For Windows, you use `. .\venv\Scripts\activate` but in [window-setup-script.bat](https://github.com/Nantawat6510545543/ku-polls/blob/main/window-setup-script.bat), you use `call .\venv\Scripts\activate`

Again, Your installation guide is awesome and it's working well, this suggestion is only my opinion on your installation.

**Comment by Nantawat6510545543** [comment]
Thank you for addressing the file conflict; this should ensure a seamless installation without any issues.
